print('good afternoon')
name = input('what is your full name?' )
print(' hello ' + name + '!')
complain = input('what is your presenting complain?' )
time = input('how long have you been having this for?' )
assosiated_symptoms = input( ' what other symptoms do you have' + name + '?' )
print( ' so ' + name + ' had complain of ' + complain + ' for ' + time + ' and other symptoms such as ' + assosiated_symptoms)
appointment = input('when are you available for consultation?' )
input(' should we book your appointment for ' + appointment + ' ? ')
print(' thankyou for contacting us ' + name + '!' + ' your appointment is scheduled for ' + appointment )
